name: Create Azure ML Workspace
run-name: ${{ github.actor }} is executing 01-create-workspace.yml

on:
  # push:
  #   branches:
  #    - 'main'
  #   paths:
  #   - 'src/model/*'
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'aibx-ml-rg'
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'aibx-mlw'
        type: string

env:
  rg: 'Replace with the name of the Azure Resource Group'
  amlw: 'Replace with the name of the AzureML Workspace Name'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Define Resource Group and Azure ML Workspace
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "rg=${{ env.rg }}" >> "$GITHUB_ENV"
            echo "amlw=${{ env.amlw }}" >> "$GITHUB_ENV"
          else
            rg="${{ github.event.inputs.resource_group }}"
            amlw="${{ github.event.inputs.aml_workspace }}"
            echo "rg=${{ github.event.inputs.resource_group }}" >> "$GITHUB_ENV"
            echo "amlw=${{ github.event.inputs.aml_workspace }}" >> "$GITHUB_ENV"
          fi

      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Create Azure ML Workspace
        run: |
          #az deployment group create --resource-group "${{ env.rg }}" --template-file ./infra/main.bicep --parameters ./infra/main.parameters.json --parameters amlworkspace="${{ env.amlw }}"
          az deployment group create --resource-group "${{ env.rg }}" --template-file ./infra/main.bicep --parameters ./infra/main.parameters.json --parameters gitHub_PAT="${{ secrets.gitHubPAT }}"
